#!/bin/bash

md izmitmp
cd izmitmp
tmp=$(mktemp)
wget https://github.com/KrzysztofSzewczyk/izmit/archive/master.zip -O $tmp
unzip $tmp
cd izmit-master
rm -rf /bin/izmit*
cp izmit* /bin
cp /bin/izmit-master /bin
rm -rf /bin/izmit-master/
cd ../..
rm -rf izmitmp $tmp
