#!/bin/bash

md izmitmp
cd izmitmp
tmp=$(mktemp)
wget https://github.com/kspalaiologos/izmit/archive/master.zip -O $tmp
unzip $tmp
cd izmit-master
rm -rf /bin/izmit*
cp izmit* /bin
cp /bin/izmit-master /bin
rm -rf /bin/izmit-master/
chmod 777 /bin/izmit*
cd ../..
rm -rf izmitmp $tmp
