#!/bin/bash

PROGNAME="make"
PREPROCESSOR=""

RESTORE=$(echo -en '\033[0m')
LBLUE=$(echo -en '\033[01;34m')
LPURPLE=$(echo -en '\033[01;35m')
LYELLOW=$(echo -en '\033[01;33m')
LRED=$(echo -en '\033[01;31m')
LGREEN=$(echo -en '\033[01;32m')

function hr {
    printf "${LGREEN}=============================================${RESTORE}\n"
}

function log_hour {
    printf "${LPURPLE}[%s]${RESTORE} " `date +"%T"`
}

function log_progname {
    printf "${LYELLOW}$PROGNAME:${RESTORE} "
}

function log {
    log_hour
    log_progname
    printf "${LBLUE}"
}

function logerr {
    log_hour
    log_progname
    printf "${LRED}"
}

hr

SRC="$1"
TARGET="$2"

if [ "$#" -ne 2 ]; then
    if [ -f "izmitfile" ]; then
        . ./izmitfile
    else
        logerr
        printf "Usage: izmitmake input.c output.b${RESTORE}\n"
        exit
    fi
fi

if [ ! -f $SRC ]; then
    logerr
    printf "FATAL: $SRC doesn't exist!${RESTORE}"
    exit
else
    log
    printf "$SRC exists.${RESTORE}\n"
fi

touch $TARGET > /dev/null 2> /dev/null
if [ ! -f $TARGET ]; then
    logerr
    printf "FATAL: Insufficient permissions to create $TARGET.${RESTORE}"
    exit
else
    log
    printf "Permissions are sufficent to continue the build.${RESTORE}\n"
    rm -f $TARGET
fi

hr

log
printf "Build started ...${RESTORE}\n"

start=`date +%s`

log
printf "Preprocessing 1/2 ...${RESTORE}\n"
gcc -E $SRC -o "${1%%.*}".i0 $PREPROCESSOR

if [ $? -ne 0 ]; then
    logerr
    printf "Preprocessor failed 1/2.${RESTORE}\n"
    exit
fi

log
printf "Optimizing ...${RESTORE}\n"
sed '/^#/ d' < "${1%%.*}".i0 > "${1%%.*}".i

if [ $? -ne 0 ]; then
    logerr
    printf "Optimizing failed.${RESTORE}\n"
    exit
fi

log
printf "Fetching $SRC ...${RESTORE}\n"
code=`cat "${1%%.*}".i`

if [ $? -ne 0 ]; then
    logerr
    printf "Couldn't fetch the source code.${RESTORE}\n"
    exit
fi

log
printf "Building libraries ...${RESTORE}\n"

libizmit=""

cd izmit_modules
for D in *; do
    if [ -d "${D}" ]; then
        cd $D
        if [ -f izmit_module.c ]; then
            libizmit+=`cat izmit_module.c`
        else
            logerr
            printf "Could not install $D - missing izmit_module.c.${RESTORE}\n"
            exit
        fi
        cd ..
    fi
done
cd ..

log
printf "Preprocessing 2/2 ...${RESTORE}\n"
totalcode="$libizmit $code main();"

if [ $? -ne 0 ]; then
    logerr
    printf "Preprocessor failed 2/2.${RESTORE}\n"
    exit
fi

log
printf "Building ...${RESTORE}\n"
echo "$totalcode" > "${1%%.*}".l
curl --form "src=$totalcode" -X POST https://uw426.mikr.us/izmit2/izmit.php > $TARGET  2> /dev/null

if [ $? -ne 0 ]; then
    logerr
    printf "Build failed.${RESTORE}\n"
    exit
fi

hr

log
printf "Cleaning up ...${RESTORE}\n"
rm -f libizmit.c "${1%%.*}".l "${1%%.*}".i "${1%%.*}".i0

if [ $? -ne 0 ]; then
    logerr
    printf "Couldn't clean up temporary files.${RESTORE}\n"
    exit
fi

end=`date +%s`
total=$((end-start))

log
printf "Build finished in %d seconds.\n\n" $total
